name: Android CI - Build APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Proje Kodunu İndir
        uses: actions/checkout@v3

      - name: 2. Java (JDK 17) Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. Gradle Wrapper'a Çalıştırma İzni Ver
        run: chmod +x android-app/gradlew
        working-directory: ./

      - name: 4. Android Uygulamasını Derle (APK Oluştur)
        run: ./gradlew assembleDebug
        working-directory: ./android-app

      - name: 5. Oluşturulan APK'yı Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: CanYoldasiAHI-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk