name: Android CI - Build APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Proje Kodunu İndir
        uses: actions/checkout@v3

      - name: 2. Java (JDK 17) Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. TEK ADIMDA DERLEME (ZORLA ÇALIŞTIRMA)
        run: |
          cd android-app
          chmod +x ./gradlew
          ./gradlew assembleDebug
        working-directory: ./

      - name: 4. Oluşturulan APK'yı Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: CanYoldasiAHI-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk